# Generated by Django 3.0.9 on 2020-08-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodList1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(max_length=25)),
                ('MinD', models.IntegerField()),
                ('MaxD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodList2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(max_length=25)),
                ('MinD', models.IntegerField()),
                ('MaxD', models.IntegerField()),
            ],
        ),
    ]
