# Generated by Django 3.0.9 on 2020-10-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeactivity',
            old_name='row_form',
            new_name='row_vid',
        ),
    ]
