# Generated by Django 3.0.9 on 2020-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0002_auto_20201009_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='row_ray',
            field=models.IntegerField(),
        ),
    ]
