# Generated by Django 3.0.9 on 2020-10-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0003_auto_20201009_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns10_code', models.IntegerField()),
                ('ns11_code', models.IntegerField()),
                ('tin', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('na1_name', models.IntegerField()),
                ('ns4_name', models.IntegerField()),
                ('gd_tin', models.CharField(max_length=255)),
                ('gd_name', models.CharField(max_length=10)),
                ('gb_tin', models.CharField(max_length=14)),
                ('gb_name', models.CharField(max_length=14)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns10_code', models.IntegerField()),
                ('ns11_code', models.IntegerField()),
                ('tin', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('series_passport', models.CharField(max_length=2)),
                ('number_passport', models.IntegerField()),
                ('org_passport', models.CharField(max_length=255)),
                ('issued_passport', models.CharField(max_length=10)),
                ('pinfl', models.CharField(max_length=14)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_str', models.CharField(max_length=3)),
                ('name_uzb', models.CharField(max_length=255)),
                ('name_rus', models.CharField(max_length=255)),
                ('s_period', models.IntegerField()),
                ('e_period', models.IntegerField()),
            ],
        ),
    ]
