# Generated by Django 3.0.9 on 2020-10-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0004_balancesheet_juridicalperson_physicalperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='sort_num',
            field=models.IntegerField(null=True),
        ),
    ]
