# Generated by Django 3.0.9 on 2020-10-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0005_balancesheet_sort_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='code_str',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='e_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='name_rus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='name_uzb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='s_period',
            field=models.IntegerField(null=True),
        ),
    ]
