# Generated by Django 3.0.9 on 2020-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0006_auto_20201012_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='balance_sect',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='balance_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='sect_name_ru',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='sect_name_uz',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
