# Generated by Django 3.0.9 on 2020-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0008_auto_20201012_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_str', models.CharField(max_length=3, null=True)),
                ('name_uzb', models.CharField(max_length=255, null=True)),
                ('name_rus', models.CharField(max_length=255, null=True)),
                ('old_per_income', models.IntegerField(null=True)),
                ('old_per_expence', models.IntegerField(null=True)),
                ('period_income', models.IntegerField(null=True)),
                ('period_expence', models.IntegerField(null=True)),
                ('sort_num', models.IntegerField(null=True)),
                ('parentid', models.IntegerField(null=True)),
            ],
        ),
    ]
