# Generated by Django 3.0.9 on 2020-10-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0009_financereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juridicalperson',
            options={},
        ),
    ]
