# Generated by Django 3.0.9 on 2020-10-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0010_auto_20201014_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juridicalperson',
            options={'managed': False},
        ),
    ]
