# Generated by Django 3.0.9 on 2020-10-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0011_auto_20201014_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuridicalPerson',
        ),
    ]
