# Generated by Django 3.0.9 on 2020-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0012_delete_juridicalperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns10_code', models.IntegerField()),
                ('ns11_code', models.IntegerField()),
                ('tin', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('na1_name', models.IntegerField()),
                ('ns4_name', models.IntegerField()),
                ('gd_tin', models.CharField(max_length=255)),
                ('gd_name', models.CharField(max_length=10)),
                ('gb_tin', models.CharField(max_length=14)),
                ('gb_name', models.CharField(max_length=14)),
            ],
        ),
    ]
