# Generated by Django 3.0.9 on 2020-10-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0013_juridicalperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridicalperson',
            name='gb_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='juridicalperson',
            name='gd_name',
            field=models.CharField(max_length=255),
        ),
    ]
