# Generated by Django 3.0.9 on 2020-10-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0014_auto_20201014_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalperson',
            options={},
        ),
    ]
