# Generated by Django 3.0.9 on 2020-10-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0016_auto_20201022_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalperson',
            options={'managed': False},
        ),
    ]
