# Generated by Django 3.0.9 on 2020-10-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0017_auto_20201022_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalPerson',
        ),
    ]
