# Generated by Django 3.0.9 on 2020-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0018_delete_physicalperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns10_code', models.IntegerField()),
                ('ns11_code', models.IntegerField()),
                ('tin', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('series_passport', models.CharField(max_length=2)),
                ('number_passport', models.IntegerField()),
                ('org_passport', models.CharField(max_length=255)),
                ('issued_passport', models.CharField(max_length=10)),
                ('pinfl', models.CharField(max_length=14)),
            ],
        ),
    ]
