# Generated by Django 3.0.9 on 2020-10-29 11:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0020_auto_20201024_1758'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='physicalperson',
            managers=[
                ('services', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='number_passport',
            field=models.IntegerField(null=True),
        ),
    ]
