# Generated by Django 3.0.9 on 2020-10-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxservices', '0021_auto_20201029_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalperson',
            name='number_passport',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
