# Generated by Django 3.0.9 on 2020-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='CODE_VAL',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
