# Generated by Django 3.0.9 on 2020-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0002_data_code_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='SCHET_KORRESPONDENT',
            field=models.CharField(max_length=25),
        ),
    ]
