# Generated by Django 3.0.9 on 2020-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0004_data_mfo_korrespondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='DATE_CREATE',
            field=models.DateTimeField(),
        ),
    ]
