# Generated by Django 3.0.9 on 2020-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0006_auto_20200811_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='DETALI_PLATEJA',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ID_DOGOVOR',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='NAIMEN_RAYON',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ZARUBEJNIY_BANK',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
