# Generated by Django 3.0.9 on 2020-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0007_auto_20200828_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BALANS_SCHET',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CODE_REGION',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CREDIT_SCHET',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ISTOCHNIK_CREDITA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='MFO',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='NAME_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='NAME_KORRESPONDENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='OTRASL_CLIENTA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PROCENT_CREDIT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PROCENT_PROSR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SCHET_KORRESPONDENT',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SEL_CREDITA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SUMMA_DOGOVOR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SUMMA_FACT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='VID_CREDITA',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
