# Generated by Django 3.0.9 on 2020-08-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('ClientName', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('ClientType', models.CharField(max_length=20, verbose_name='Тип клиента')),
                ('TotalLoans', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Всего задолженность')),
                ('Address', models.CharField(max_length=255, verbose_name='Адрес клиента')),
                ('Status', models.IntegerField(verbose_name='Статус клиент')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataForLineChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=5)),
                ('Total', models.FloatField()),
                ('Prosr', models.FloatField()),
                ('Reserv', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Показатели')),
                ('Old_Value', models.CharField(max_length=255, verbose_name='Предыдущий  месяц')),
                ('New_Value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Текущий месяц')),
                ('Updates', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение')),
                ('Percent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение, %')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
