# Generated by Django 3.1.3 on 2020-11-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePogash', models.DateField(verbose_name='Дата погашения')),
                ('PrognozPogash', models.FloatField(verbose_name='Прогноз погашения')),
                ('OstatokPercent', models.FloatField(verbose_name='Остаток нач. процент')),
                ('CurrencyName', models.CharField(max_length=10, verbose_name='Валюта')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
    ]
