# Generated by Django 3.0.9 on 2020-10-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_ecosphere_industry_oked_oknx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oked',
            name='ecosphere',
        ),
        migrations.RemoveField(
            model_name='oked',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='oknx',
            name='ecosphere',
        ),
        migrations.RemoveField(
            model_name='oknx',
            name='industry',
        ),
        migrations.DeleteModel(
            name='EcoSphere',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='OKED',
        ),
        migrations.DeleteModel(
            name='OKNX',
        ),
    ]
