# Generated by Django 3.0.9 on 2020-10-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_ecosphere_industry_oked_oknx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosphere',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sphere_industry', to='references.Industry'),
        ),
    ]
