# Generated by Django 3.0.9 on 2020-10-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20201013_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oked',
            name='sect',
        ),
        migrations.RemoveField(
            model_name='oknx',
            name='sect',
        ),
        migrations.AddField(
            model_name='oked',
            name='sect_code',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='oked',
            name='sect_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oknx',
            name='sect_code',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='oknx',
            name='sect_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
