# Generated by Django 3.0.9 on 2020-10-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20201013_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oked',
            name='ecosphere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oked_sphere', to='references.EcoSphere'),
        ),
        migrations.AlterField(
            model_name='oked',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oked_industry', to='references.Industry'),
        ),
        migrations.AlterField(
            model_name='oknx',
            name='ecosphere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oknx_sphere', to='references.EcoSphere'),
        ),
        migrations.AlterField(
            model_name='oknx',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oknx_industry', to='references.Industry'),
        ),
    ]
