# Generated by Django 3.0.9 on 2020-10-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20201013_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oknx',
            name='sect_code',
        ),
        migrations.RemoveField(
            model_name='oknx',
            name='sect_name',
        ),
    ]
