# Generated by Django 3.0.9 on 2020-10-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20201013_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oknx',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
