# Generated by Django 3.0.9 on 2020-10-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_auto_20201013_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OKNX',
        ),
    ]
