# Generated by Django 3.0.9 on 2020-10-13 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_delete_oknx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKNX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ecosphere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oknx_sphere', to='references.EcoSphere')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oknx_industry', to='references.Industry')),
            ],
        ),
    ]
